### PR TITLE
[MRG] Fix numerical issue in expectation step

### LINKED ISSUE #30: Numerical problems lead to worse scores in comparison to sklearn
Relevant examples at the and of this pull request: https://github.com/AlexanderFabisch/gmr/pull/28 from @mralbu 

> Did some additional comparisons with an [experiment](https://github.com/mralbu/scikit-lego/blob/GMMRegressor/sklego/mixture/gmm_regressor.py#L8) using sklearn.mixture.GaussianMixture machinery for fitting the regressor.
> 
> ```python
> from sklego.mixture import GMMRegressor
> 
> np.set_printoptions(precision=4)
> 
> np.random.seed(2)
> 
> scores = []
> for _ in range(10):
>     gmr = GMMRegressor(n_components=2)
>     gmr.fit(X, y)
>     scores.append(gmr.score(X, y))
> print(np.array(scores))
> >> [0.8478 0.8478 0.8478 0.8478 0.8478 0.8478 0.8478 0.8478 0.8478 0.8478]
> 
> np.random.seed(2)
> 
> scores = []
> for _ in range(10):
>     gmr = GMMRegressor(n_components=2, init_params='random', max_iter=100)
>     gmr.fit(X, y)
>     scores.append(gmr.score(X, y))
> print(np.array(scores))
> >> [0.8157 0.8061 0.8221 0.8152 0.8221 0.8192 0.8479 0.8282 0.8251 0.7792]
> ```
> 
> Maybe using internal sklearn.mixture machinery might help ease numerical issues, though it would introduce sklearn as a hard dependency and might be out of scope. On the other hand, it would enable the introduction of other regressors such as [BayesianGMMRegressor](https://github.com/mralbu/scikit-lego/blob/GMMRegressor/sklego/mixture/bayesian_gmm_regressor.py#L9) in an easy way, and would have familiar parameters (the same as in sklearn.mixture.GaussianMixture). Do you think exploring the use of sklearn.mixture inner workings would be interesting for gmr?

* I guess the main reason why sklearn's GaussianMixture produces better results is their implementation of the expectation step: https://github.com/scikit-learn/scikit-learn/blob/138da7ea911274f34d28849337c2768d7e3a7a96/sklearn/mixture/_base.py#L462
* I am not completely happy with the covariance shrinkage at the moment, this could be removed before the release of version 1.6
* First observation: `init_params="kmeans++"` drastically improves stability of our results, it is not the default initialization though

### PR DESCRIPTION
**Pull request by AlexanderFabisch**
Fixes #30

### CODE REVIEW

**Comment by AlexanderFabisch** [comment]
@mralbu If you have no time for this, it is OK, but I'd like to ask you one last time whether you can take a look at these fixes. With the test code from #30 it looks quite good now. With random initialization I get scores similar to sklearn. sklearn is also able to initialize from KMeans, which gives slightly better results than kmeans++ initialization, but it is out of scope for this library.

**Comment by mralbu** [comment]
Using test code from [#30](https://github.com/AlexanderFabisch/gmr/issues/30#issuecomment-820303956), and the experimental [GMMRegressor](https://github.com/mralbu/scikit-lego/blob/GMMRegressor/sklego/mixture/gmm_regressor.py) with sklearn internals.

Results look good, scores from random init are practically the same!
Did some timings as well, and sklearn internals are quite a bit faster. In particular, kmeans initialization is faster than random init for the experimental GMMRegressor, but not for gmr. 

```python
import numpy as np
from sklearn.datasets import load_boston

X, y = load_boston(return_X_y=True)

np.set_printoptions(precision=2, suppress=True)

np.random.seed(2)

start = time.time()
scores = []
for _ in range(10):
    gmr = GaussianMixtureRegressor(
        n_components=2, init_params="kmeans++")
    gmr.fit(X, y)
    score = gmr.score(X, y)
    scores.append(score)
print(str(np.array(scores)) + f" in {(time.time() - start):.3f} seconds")
>> [0.81 0.83 0.77 0.82 0.83 0.83 0.77 0.83 0.82 0.83] in 3.108 seconds

np.random.seed(2)

start = time.time()
scores = []
for _ in range(10):
    gmr = GaussianMixtureRegressorSklearn(
        n_components=2, init_params="random")
    gmr.fit(X, y)
    score = gmr.score(X, y)
    scores.append(score)
print(str(np.array(scores)) + f" in {(time.time() - start):.3f} seconds")
>> [0.82 0.81 0.82 0.82 0.82 0.81 0.85 0.83 0.83 0.78] in 2.877 seconds

from sklego.mixture import GMMRegressor

np.random.seed(2)
start = time.time()
scores = []
for _ in range(10):
    gmr = GMMRegressor(n_components=2, init_params="random")
    gmr.fit(X, y)
    score = gmr.score(X, y)
    scores.append(score)
    
print(str(np.array(scores)) + f" in {(time.time() - start):.3f} seconds")
>> [0.82 0.81 0.82 0.82 0.82 0.82 0.85 0.83 0.83 0.78] in 0.091 seconds 

np.random.seed(2)
start = time.time()
scores = []
for _ in range(10):
    gmr = GMMRegressor(n_components=2, init_params="kmeans")
    gmr.fit(X, y)
    score = gmr.score(X, y)
    scores.append(score)

print(str(np.array(scores)) + f" in {(time.time() - start):.3f} seconds")
>> [0.85 0.85 0.85 0.85 0.85 0.85 0.85 0.85 0.85 0.85] in 0.042 seconds
```

**Comment by AlexanderFabisch** [comment]
> Did some timings as well, and sklearn internals are quite a bit faster. In particular, kmeans initialization is faster than random init for the experimental GMMRegressor, but not for gmr.

Thanks for checking.

I think I don't understand this:

1. GaussianMixtureRegressor + kmeans++: 3.1 s
2. GaussianMixtureRegressorSklearn + random: 2.9 s
3. GMMRegressor + random: 0.09 s
4. GMMRegressor + kmeans: 0.04 s

2. and 3. should give very similar results, shouldn't they?

**Comment by mralbu** [comment]
That's true!
I think the bulk of the difference is in the prediction step.
Reran the benchmarks commenting out the prediction, and the timings for 2 and 3 are very similar:

```python
np.random.seed(2)

start = time.time()
scores = []
for _ in range(10):
    gmr = GaussianMixtureRegressor(
        n_components=2, init_params="kmeans++")
    gmr.fit(X, y)

print(f" in {(time.time() - start):.3f} seconds")
>> in 0.163 seconds

np.random.seed(2)

start = time.time()
scores = []
for _ in range(10):
    gmr = GaussianMixtureRegressorSklearn(
        n_components=2, init_params="random")
    gmr.fit(X, y)

print(f" in {(time.time() - start):.3f} seconds")
>> in 0.090 seconds 

from sklego.mixture import GMMRegressor

np.random.seed(2)
start = time.time()
scores = []
for _ in range(10):
    gmr = GMMRegressor(n_components=2, init_params="random")
    gmr.fit(X, y)
    
print(f" in {(time.time() - start):.3f} seconds")
>> in 0.082 seconds

np.random.seed(2)
start = time.time()
scores = []
for _ in range(10):
    gmr = GMMRegressor(n_components=2, init_params="kmeans")
    gmr.fit(X, y)

print(f" in {(time.time() - start):.3f} seconds")
>> in 0.034 seconds
```

**Comment by AlexanderFabisch** [comment]
OK, thanks! I will merge it then soon.

**Comment by AlexanderFabisch** [comment]
I'll probably also include a prediction function similar to yours in the future as it is so much faster (if that is OK for you and licenses are compatible). :)

**Comment by mralbu** [comment]
Sure, that's ok! You can use any of the code in [GMMRegressor](https://github.com/mralbu/scikit-lego/blob/GMMRegressor/sklego/mixture/gmm_regressor.py), even all of it if you think it would be a good adition. 
I thought it would be interesting to be able to use other sklearn.mixture.GaussianMixture options, such as different covariance_types and the BayesianGaussianMixture.

**Comment by AlexanderFabisch** [comment]
Thanks again @mralbu

**Pull request merged**
